---
- name: Get from iTop a list of hosts defined by an OQL
  hosts: localhost

  vars:
    url: "{{ itop_root }}/webservices/rest.php?version={{ itop_ws_version }}"
    file: "{{ local_inventory_path }}/{{ local_inventory_name }}.txt"

  tasks:
    - name: Call operation ansible/get_hosts_by_oql
      ansible.builtin.uri:
        url: "{{ url }}"
        method: POST
        force_basic_auth: true
        url_username: "{{ itop_ws_auth_user }}" 
        url_password: "{{ itop_ws_auth_pwd }}"
        body: json_data= {
          "operation":"ansible/get_hosts_by_oql",
          "uuid":"{{ itop_ws_ansible_uuid }}",
          "inventory":"{{ itop_ws_ansible_inventory }}",
          "oql":"{{ itop_ws_ansible_oql_for_hosts }}",
          "attribute":"{{ itop_ws_ansible_attribute }}"
          }
        return_content: true
      register: response 

    - name: Save the Json data
      ansible.builtin.set_fact:
        jsondata: "{{ response.content | from_json }}"

    - name: Get error code and message
      ansible.builtin.set_fact:
        error_code: "{{ jsondata | json_query('code') }}"
        error_message: "{{ jsondata | json_query('message') }}"

    - name: Display error, if any
      ansible.builtin.debug:
        var: error_message
      when: error_code != "0"

    - name: Get list of hosts
      ansible.builtin.set_fact:
        hosts_list: "{{ jsondata | json_query('objects.*.text_file') }}"
      when: error_code == "0"

    - name: Save result in file
      ansible.builtin.copy:
        content: "{{ hosts_list[0] }}"
        dest: "{{ file }}"
      when: error_code == "0" and hosts_in_file == True

    - name: Save list for reusability
      ansible.builtin.set_fact:
        itop_hosts: "{{ hosts_list[0] }}"
      when: error_code == "0"
